### PR TITLE
Use genevent for plugins

### PR DESCRIPTION
**Pull request by keathley**
# Why

I added a simple genevent manager so that plugins can listen to new messages that the adapter hears. Its partially based off of @colinrymer's work (which is excellent btw!).  I wanted to create my own version of it just to learn a bit more about how it works and as a comparison point. I've also started adding some tests. There aren't a ton there yet but I figured we had to start somewhere. Let me know what you think.
## Api choices

I decided to create two methods; `hear/2` and `respond/2`. Respond listens to any messages prefaced with the bots name, such as `butler cowsay hello`. `hear/2` can be used to listen to all other messages. Both functions can return either a `{:noreply, state}` tuple or a `{:reply, "some reply message", state}` tuple. 

In order to create a handler the user now simply has to do this:

``` elixir
defmodule SomePlugin.MyPlugin do
  use Butler.Plugin

  def hear(msg, state) do
    if Regex.match?(~r/meh/, msg) do
      state.mehs = state.mehs + 1
    end

    {:noreply, state}
  end

  def respond("how much meh", state) do
    {:reply, "the meh is at #{state.mehs}", state}
  end
end
```

and add that plugin to the plugin list in `mix.exs`

``` elixir
#mix.exs

defmodule Butler.Mixfile do
  # ...
  def plugins do
    [ {SomePlugin.MyPlugin, []} ]
  end
end
```

I like the idea of adding the plugin list directly to the mix file since eventually I would like the bot to either install the plugins that are listed, or generate the list from the installed plugins.

Let me know if you have any feedback.

### CODE REVIEW

**Comment by colinrymer** [comment]
So one of the decisions I made in my spike was to have a plugin module's response look something like `{:reply, {:code, "<the reply>"}` where `:code` indicated that the module responsible for the output of the reply should format it appropriately, e.g. adding the triple backticks for Slack and "/code" for HipChat. So far, potential descriptors I've identified are `:code`, `:quote`, and `:text`.

**Comment by keathley** [comment]
`emote` might be another one. 

I think thats a great solution for allowing multiple adapters. I'd be interested to see an implementation of a non-slack adapter to see how it would work to drop in other adapters. Specifically it would be great to see a shell adapter for development purposes. Might be worth spiking on.

That said is that something that we need to do now or is it something that we can do once we have pluggable adapters?

**Comment by colinrymer** [comment]
I'd go ahead and setup the response to use the tuple with the response type - it's not much change that needs to be made to slack, and it'll make the implementation of adapters and plugins much simpler (e.g. the the shell adapter could just print the type and then the response with no additional formatting).

**Comment by colinrymer** [comment]
The shell responder could look something like:

``` elixir
defmodule Butler.Responder.Shell do
  use Butler.Responder

  def reply({type, message}) do
      IO.puts "Type: #{type}"
      IO.puts message
  end
end
```

**Comment by keathley** [comment]
I'll update the implementation to use the tuple.

**Comment by colinrymer** [comment]
Cool. Thoughts on `Butler.Adapter` vs `Butler.Listener` and `Butler.Responder`?

I think `Butler.Adapter` is nice in that you're only having to setup one file, but that seems like a violation of SRP and it's nice being able to setup multiple Responders without adding Listeners.

**Comment by keathley** [comment]
I personally prefer `Butler.Adapter`.  Doing it all in one module is fine for now IMO.

**Pull request merged**
