### PR TITLE
Spike/hear api

### PR DESCRIPTION
**Pull request by keathley**
First pass at an api for plugins and message handlers.

### CODE REVIEW

**Comment by bbrock25** [comment]
@keathley did you see @colinrymer's PR [here](https://github.com/colinrymer/butler/commit/1245f67ea8da5c11ae6835d83f5c6d6e33567cdc) 
not sure if its the same direction that you're going in, but it seems like a cool approach.

**Comment by bbrock25** [comment]
either way, I like this as a simple, extendable starting point.

**Comment by keathley** [comment]
Yeah I talked to him about it.  It's definitely the direction we want to go.  The plan is to merge this in for now, cut a tag, and then merge in @colinrymer's changes.  That way we have a "stable version" tagged and we can just move forward with the new design.

**Comment by bbrock25** [comment]
I like it :)

**Pull request merged**
